var heroes = [{
    id: "ana",
    name: "Ana",
    img: 'img/ana.png'
  },
  {
    id: "ashe",
    name: "Ashe",
    img: 'img/ashe.png'
  }, {
    id: "baptiste",
    name: "Baptiste",
    img: 'img/baptiste.png'
  }, {
    id: "brigitte",
    name: "Brigitte",
    img: 'img/brigitte.png'
  }, {
    id: "bastion",
    name: "Bastion",
    img: 'img/bastion.png'
  }, {
    id: "doomfist",
    name: "Doomfist",
    img: 'img/doomfist.png'
  }, {
    id: "dVa",
    name: "D.va",
    img: 'img/dva.png'
  }, {
    id: "genji",
    name: "Genji",
    img: 'img/genji.png'
  }, {
    id: "hanzo",
    name: "Hanzo",
    img: 'img/hanzo.png'
  }, {
    id: "junkrat",
    name: "Junkrat",
    img: 'img/junkrat.png'
  }, {
    id: "lucio",
    name: "Lucio",
    img: 'img/lucio.png'
  }, {
    id: "mccree",
    name: "McCree",
    img: 'img/mccree.png'
  }, {
    id: "mei",
    name: "Mei",
    img: 'img/mei.png'
  }, {
    id: "mercy",
    name: "Mercy",
    img: 'img/mercy.png'
  }, {
    id: "moira",
    name: "Moira",
    img: 'img/moira.png'
  }, {
    id: "orisa",
    name: "Orisa",
    img: 'img/orisa.png'
  }, {
    id: "pharah",
    name: "Pharah",
    img: 'img/phara.png'
  }, {
    id: "reaper",
    name: "Reaper",
    img: 'img/reaper.png'
  }, {
    id: "reinhardt",
    name: "Reinhardt",
    img: 'img/reinhart.png'
  }, {
    id: "roadhog",
    name: "Roadhog",
    img: 'img/roadhog.png'
  }, {
    id: "soldier76",
    name: "Soldier 76",
    img: 'img/soldier.png'
  }, {
    id: "sombra",
    name: "Sombra",
    img: 'img/sombra.png'
  }, {
    id: "symmetra",
    name: "Symmetra",
    img: 'img/symmetra.png'
  }, {
    id: "torbjorn",
    name: "Torbjorn",
    img: 'img/torbjorn.png'
  }, {
    id: "tracer",
    name: "Tracer",
    img: 'img/tracer.png'
  }, {
    id: "widowmaker",
    name: "Widowmaker",
    img: 'img/widowmaker.png'
  }, {
    id: "winston",
    name: "Winston",
    img: 'img/winston.png'
  }, {
    id: "wreckingBall",
    name: "Wrecking Ball",
    img: 'img/wrecking.png'
  }, {
    id: "zarya",
    name: "Zarya",
    img: 'img/zarya.png'
  }, {
    id: "zenyatta",
    name: "Zenyatta",
    img: 'img/zenyatta.png'
  },
]
